#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 UPR.
#
# Cuban Organizations Registry is free software; you can redistribute it
# and/or modify it under the terms of the MIT License; see LICENSE file for
# more details.

set -e

script_path=$(dirname "$0")

export FLASK_ENV=development
# Start Worker and Server
#pipenv run celery worker -A invenio_app.celery -l INFO & pid_celery=$!

#pipenv run invenio run \
#       --port 5001 \
#       --cert "$script_path"/../docker/nginx/test.crt \
#       --key "$script_path"/../docker/nginx/test.key \
#       --host "192.168.1.100" & pid_server=$!

pipenv run invenio run \
       --port 5001 \
       --cert "$script_path"/../docker/nginx/test.crt \
       --key "$script_path"/../docker/nginx/test.key \
       --host "192.168.1.102" \
       & pid_server=$!

trap 'kill $pid_celery $pid_server &>/dev/null' EXIT

wait $pid_celery $pid_server
