#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 UPR.
#
# Cuban Organizations Registry is free software; you can redistribute it
# and/or modify it under the terms of the MIT License; see LICENSE file for
# more details.

set -e


# Clean redis
pipenv run invenio shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
#pipenv run invenio db destroy --yes-i-know
pipenv run invenio db drop --yes-i-know
pipenv run invenio db create
pipenv run invenio index destroy --force --yes-i-know
pipenv run invenio index init --force
pipenv run invenio index queue init purge
pipenv run invenio files location --default 'default-location'  $(pipenv run invenio shell --no-term-title -c "print(app.instance_path)")'/data'

# Create admin role to restrict access
pipenv run invenio roles create admin
pipenv run invenio access allow superuser-access role admin

pipenv run invenio users create --password "1qazxsw2" --active  eduardo.arencibia@upr.edu.cu
pipenv run invenio roles add eduardo.arencibia@upr.edu.cu admin

pipenv run invenio harvester loadgrid
pipenv run invenio harvester gettoporg
pipenv run invenio harvester getlowerorg